name: 🐞 Bug Report
description: Create a report to help us improve the Stencil Framework Output Targets
title: 'bug: '
labels: ['pending triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please provide a minimal reproduction using one of our starter templates:
        - **Angular**: [CodeSandbox](https://codesandbox.io/p/github/johnjenkins/stencil-angular-starter/)
        - **React**: [CodeSandbox](https://codesandbox.io/p/github/johnjenkins/stencil-starter-react/)
        - **Vue**: [CodeSandbox](https://codesandbox.io/p/github/johnjenkins/stencil-starter-vue/)

        A minimal reproduction is **required** unless you are absolutely sure the issue is obvious.
        If the issue cannot be reliably reproduced, it will be labeled `needs reproduction` and may be closed.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please ensure you have completed all of the following.
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: I have searched for [existing issues](https://github.com/stenciljs/output-targets/issues) that already report this problem, without success.
          required: true

  - type: dropdown
    id: framework
    attributes:
      label: Framework Output Target
      description: Which framework output target does this issue relate to?
      options:
        - Angular (@stencil/angular-output-target)
        - React (@stencil/react-output-target)
        - Vue (@stencil/vue-output-target)
        - SSR (@stencil/ssr)
        - Multiple / Other
    validations:
      required: true

  - type: input
    attributes:
      label: Output Target Version
      description: The version of the output target package you are using.
      placeholder: e.g., 0.8.0
    validations:
      required: true

  - type: input
    attributes:
      label: Stencil Version
      description: The version of @stencil/core you are using.
      placeholder: e.g., 4.0.0
    validations:
      required: true

  - type: input
    attributes:
      label: Reproduction URL
      description: |
        Please provide a link to a reproduction. Use one of our starter templates:
        - [Angular](https://codesandbox.io/p/github/johnjenkins/stencil-angular-starter/)
        - [React](https://codesandbox.io/p/github/johnjenkins/stencil-starter-react/)
        - [Vue](https://codesandbox.io/p/github/johnjenkins/stencil-starter-vue/)
      placeholder: https://codesandbox.io/p/...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (e.g., screenshots, logs, related issues).

  - type: textarea
    attributes:
      label: Logs
      description: |
        Optional if provided reproduction. Please try not to insert an image but copy paste the log text.
      render: shell-session
