/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';
import { MyButtonScoped as MyButtonScopedElement } from 'component-library/components/my-button-scoped.js';

export const serializeShadowRoot: SerializeShadowRootOptions = {
  scoped: ['my-counter'],
  default: 'declarative-shadow-dom',
};

export type MyButtonScopedEvents = {
  onMyFocus: EventName<CustomEvent<void>>;
  onMyBlur: EventName<CustomEvent<void>>;
};

export const MyButtonScoped: StencilReactComponent<MyButtonScopedElement, MyButtonScopedEvents> =
  /*@__PURE__*/ createComponent<MyButtonScopedElement, MyButtonScopedEvents>({
    tagName: 'my-button-scoped',
    properties: {
      color: 'color',
      buttonType: 'button-type',
      disabled: 'disabled',
      expand: 'expand',
      fill: 'fill',
      download: 'download',
      href: 'href',
      rel: 'rel',
      shape: 'shape',
      size: 'size',
      strong: 'strong',
      target: 'target',
      type: 'type',
    },
    hydrateModule: import('component-library/hydrate'),
    serializeShadowRoot,
  });
