'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import {
  MyButtonScoped as MyButtonScopedElement,
  defineCustomElement as defineMyButtonScoped,
} from 'component-library/components/my-button-scoped.js';
import React from 'react';

export type MyButtonScopedEvents = {
  onMyFocus: EventName<CustomEvent<void>>;
  onMyBlur: EventName<CustomEvent<void>>;
};

export const MyButtonScoped: StencilReactComponent<MyButtonScopedElement, MyButtonScopedEvents> =
  /*@__PURE__*/ createComponent<MyButtonScopedElement, MyButtonScopedEvents>({
    tagName: 'my-button-scoped',
    elementClass: MyButtonScopedElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
      onMyFocus: 'myFocus',
      onMyBlur: 'myBlur',
    } as MyButtonScopedEvents,
    defineCustomElement: defineMyButtonScoped,
  });
