'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import {
  MyButton as MyButtonElement,
  defineCustomElement as defineMyButton,
} from 'component-library/components/my-button.js';
import React from 'react';

export type MyButtonEvents = {
  onMyFocus: EventName<CustomEvent<void>>;
  onMyBlur: EventName<CustomEvent<void>>;
};

export const MyButton: StencilReactComponent<MyButtonElement, MyButtonEvents> = /*@__PURE__*/ createComponent<
  MyButtonElement,
  MyButtonEvents
>({
  tagName: 'my-button',
  elementClass: MyButtonElement,
  // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
  react: React,
  events: {
    onMyFocus: 'myFocus',
    onMyBlur: 'myBlur',
  } as MyButtonEvents,
  defineCustomElement: defineMyButton,
});
