'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type IMyComponent, type MyComponentScopedCustomEvent } from 'component-library';
import {
  MyComponentScoped as MyComponentScopedElement,
  defineCustomElement as defineMyComponentScoped,
} from 'component-library/components/my-component-scoped.js';
import React from 'react';

export type MyComponentScopedEvents = {
  onMyCustomEvent: EventName<MyComponentScopedCustomEvent<IMyComponent.someVar>>;
};

export const MyComponentScoped: StencilReactComponent<MyComponentScopedElement, MyComponentScopedEvents> =
  /*@__PURE__*/ createComponent<MyComponentScopedElement, MyComponentScopedEvents>({
    tagName: 'my-component-scoped',
    elementClass: MyComponentScopedElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onMyCustomEvent: 'myCustomEvent' } as MyComponentScopedEvents,
    defineCustomElement: defineMyComponentScoped,
  });
