'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type CheckboxChangeEventDetail, type MyCheckboxCustomEvent } from 'component-library';
import {
  MyCheckbox as MyCheckboxElement,
  defineCustomElement as defineMyCheckbox,
} from 'component-library/components/my-checkbox.js';
import React from 'react';

export type MyCheckboxEvents = {
  onIonChange: EventName<MyCheckboxCustomEvent<CheckboxChangeEventDetail>>;
  onIonFocus: EventName<CustomEvent<void>>;
  onIonBlur: EventName<CustomEvent<void>>;
};

export const MyCheckbox: StencilReactComponent<MyCheckboxElement, MyCheckboxEvents> = /*@__PURE__*/ createComponent<
  MyCheckboxElement,
  MyCheckboxEvents
>({
  tagName: 'my-checkbox',
  elementClass: MyCheckboxElement,
  // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
  react: React,
  events: {
    onIonChange: 'ionChange',
    onIonFocus: 'ionFocus',
    onIonBlur: 'ionBlur',
  } as MyCheckboxEvents,
  defineCustomElement: defineMyCheckbox,
});
