/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';
import { type CheckboxChangeEventDetail, type MyCheckboxCustomEvent } from 'component-library';
import { MyCheckbox as MyCheckboxElement } from 'component-library/components/my-checkbox.js';

export const serializeShadowRoot: SerializeShadowRootOptions = {
  scoped: ['my-counter'],
  default: 'declarative-shadow-dom',
};

export type MyCheckboxEvents = {
  onIonChange: EventName<MyCheckboxCustomEvent<CheckboxChangeEventDetail>>;
  onIonFocus: EventName<CustomEvent<void>>;
  onIonBlur: EventName<CustomEvent<void>>;
};

export const MyCheckbox: StencilReactComponent<MyCheckboxElement, MyCheckboxEvents> = /*@__PURE__*/ createComponent<
  MyCheckboxElement,
  MyCheckboxEvents
>({
  tagName: 'my-checkbox',
  properties: {
    color: 'color',
    name: 'name',
    checked: 'checked',
    indeterminate: 'indeterminate',
    disabled: 'disabled',
    value: 'value',
    labelPlacement: 'label-placement',
    justify: 'justify',
    alignment: 'alignment',
  },
  hydrateModule: import('component-library/hydrate'),
  serializeShadowRoot,
});
