'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import {
  MyComponent as MyComponentElement,
  defineCustomElement as defineMyComponent,
} from 'component-library/components/my-component.js';
import React from 'react';

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<
  MyComponentElement,
  MyComponentEvents
>({
  tagName: 'my-component',
  elementClass: MyComponentElement,
  // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
  react: React,
  events: {} as MyComponentEvents,
  defineCustomElement: defineMyComponent,
});
