'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import {
  MyCounter as MyCounterElement,
  defineCustomElement as defineMyCounter,
} from 'component-library/components/my-counter.js';
import React from 'react';

export type MyCounterEvents = { onCount: EventName<CustomEvent<number>> };

export const MyCounter: StencilReactComponent<MyCounterElement, MyCounterEvents> = /*@__PURE__*/ createComponent<
  MyCounterElement,
  MyCounterEvents
>({
  tagName: 'my-counter',
  elementClass: MyCounterElement,
  // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
  react: React,
  events: { onCount: 'count' } as MyCounterEvents,
  defineCustomElement: defineMyCounter,
});
