/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';
import { MyCounter as MyCounterElement } from 'component-library/components/my-counter.js';

export const serializeShadowRoot: SerializeShadowRootOptions = {
  scoped: ['my-counter'],
  default: 'declarative-shadow-dom',
};

export type MyCounterEvents = { onCount: EventName<CustomEvent<number>> };

export const MyCounter: StencilReactComponent<MyCounterElement, MyCounterEvents> = /*@__PURE__*/ createComponent<
  MyCounterElement,
  MyCounterEvents
>({
  tagName: 'my-counter',
  properties: { startValue: 'start-value' },
  hydrateModule: import('component-library/hydrate'),
  serializeShadowRoot,
});
