/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';
import { MyListItem as MyListItemElement } from 'component-library/components/my-list-item.js';

export const serializeShadowRoot: SerializeShadowRootOptions = {
  scoped: ['my-counter'],
  default: 'declarative-shadow-dom',
};

export type MyListItemEvents = NonNullable<unknown>;

export const MyListItem: StencilReactComponent<MyListItemElement, MyListItemEvents> = /*@__PURE__*/ createComponent<
  MyListItemElement,
  MyListItemEvents
>({
  tagName: 'my-list-item',
  properties: {},
  hydrateModule: import('component-library/hydrate'),
  serializeShadowRoot,
});
