'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import {
  MyListItem as MyListItemElement,
  defineCustomElement as defineMyListItem,
} from 'component-library/components/my-list-item.js';
import React from 'react';

export type MyListItemEvents = NonNullable<unknown>;

export const MyListItem: StencilReactComponent<MyListItemElement, MyListItemEvents> = /*@__PURE__*/ createComponent<
  MyListItemElement,
  MyListItemEvents
>({
  tagName: 'my-list-item',
  elementClass: MyListItemElement,
  // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
  react: React,
  events: {} as MyListItemEvents,
  defineCustomElement: defineMyListItem,
});
