'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import {
  MyListScoped as MyListScopedElement,
  defineCustomElement as defineMyListScoped,
} from 'component-library/components/my-list-scoped.js';
import React from 'react';

export type MyListScopedEvents = NonNullable<unknown>;

export const MyListScoped: StencilReactComponent<MyListScopedElement, MyListScopedEvents> =
  /*@__PURE__*/ createComponent<MyListScopedElement, MyListScopedEvents>({
    tagName: 'my-list-scoped',
    elementClass: MyListScopedElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as MyListScopedEvents,
    defineCustomElement: defineMyListScoped,
  });
