'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { MyList as MyListElement, defineCustomElement as defineMyList } from 'component-library/components/my-list.js';
import React from 'react';

export type MyListEvents = NonNullable<unknown>;

export const MyList: StencilReactComponent<MyListElement, MyListEvents> = /*@__PURE__*/ createComponent<
  MyListElement,
  MyListEvents
>({
  tagName: 'my-list',
  elementClass: MyListElement,
  // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
  react: React,
  events: {} as MyListEvents,
  defineCustomElement: defineMyList,
});
