'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type MyPopoverCustomEvent, type OverlayEventDetail } from 'component-library';
import {
  MyPopover as MyPopoverElement,
  defineCustomElement as defineMyPopover,
} from 'component-library/components/my-popover.js';
import React from 'react';

export type MyPopoverEvents = {
  onMyPopoverDidPresent: EventName<CustomEvent<void>>;
  onMyPopoverWillPresent: EventName<CustomEvent<void>>;
  onMyPopoverWillDismiss: EventName<MyPopoverCustomEvent<OverlayEventDetail>>;
  onMyPopoverDidDismiss: EventName<MyPopoverCustomEvent<OverlayEventDetail>>;
};

export const MyPopover: StencilReactComponent<MyPopoverElement, MyPopoverEvents> = /*@__PURE__*/ createComponent<
  MyPopoverElement,
  MyPopoverEvents
>({
  tagName: 'my-popover',
  elementClass: MyPopoverElement,
  // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
  react: React,
  events: {
    onMyPopoverDidPresent: 'myPopoverDidPresent',
    onMyPopoverWillPresent: 'myPopoverWillPresent',
    onMyPopoverWillDismiss: 'myPopoverWillDismiss',
    onMyPopoverDidDismiss: 'myPopoverDidDismiss',
  } as MyPopoverEvents,
  defineCustomElement: defineMyPopover,
});
