/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';
import { type MyPopoverCustomEvent, type OverlayEventDetail } from 'component-library';
import { MyPopover as MyPopoverElement } from 'component-library/components/my-popover.js';

export const serializeShadowRoot: SerializeShadowRootOptions = {
  scoped: ['my-counter'],
  default: 'declarative-shadow-dom',
};

export type MyPopoverEvents = {
  onMyPopoverDidPresent: EventName<CustomEvent<void>>;
  onMyPopoverWillPresent: EventName<CustomEvent<void>>;
  onMyPopoverWillDismiss: EventName<MyPopoverCustomEvent<OverlayEventDetail>>;
  onMyPopoverDidDismiss: EventName<MyPopoverCustomEvent<OverlayEventDetail>>;
};

export const MyPopover: StencilReactComponent<MyPopoverElement, MyPopoverEvents> = /*@__PURE__*/ createComponent<
  MyPopoverElement,
  MyPopoverEvents
>({
  tagName: 'my-popover',
  properties: {
    component: 'component',
    componentProps: 'component-props',
    keyboardClose: 'keyboard-close',
    cssClass: 'css-class',
    backdropDismiss: 'backdrop-dismiss',
    event: 'event',
    showBackdrop: 'show-backdrop',
    translucent: 'translucent',
    animated: 'animated',
  },
  hydrateModule: import('component-library/hydrate'),
  serializeShadowRoot,
});
