/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';
import { type MyRangeCustomEvent, type RangeChangeEventDetail } from 'component-library';
import { MyRange as MyRangeElement } from 'component-library/components/my-range.js';

export const serializeShadowRoot: SerializeShadowRootOptions = {
  scoped: ['my-counter'],
  default: 'declarative-shadow-dom',
};

export type MyRangeEvents = {
  onMyChange: EventName<MyRangeCustomEvent<RangeChangeEventDetail>>;
  onMyFocus: EventName<CustomEvent<void>>;
  onMyBlur: EventName<CustomEvent<void>>;
};

export const MyRange: StencilReactComponent<MyRangeElement, MyRangeEvents> = /*@__PURE__*/ createComponent<
  MyRangeElement,
  MyRangeEvents
>({
  tagName: 'my-range',
  properties: {
    color: 'color',
    debounce: 'debounce',
    name: 'name',
    dualKnobs: 'dual-knobs',
    min: 'min',
    max: 'max',
    pin: 'pin',
    snaps: 'snaps',
    step: 'step',
    ticks: 'ticks',
    disabled: 'disabled',
    value: 'value',
  },
  hydrateModule: import('component-library/hydrate'),
  serializeShadowRoot,
});
