'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import {
  MyRadio as MyRadioElement,
  defineCustomElement as defineMyRadio,
} from 'component-library/components/my-radio.js';
import React from 'react';

export type MyRadioEvents = {
  onIonFocus: EventName<CustomEvent<void>>;
  onIonBlur: EventName<CustomEvent<void>>;
};

export const MyRadio: StencilReactComponent<MyRadioElement, MyRadioEvents> = /*@__PURE__*/ createComponent<
  MyRadioElement,
  MyRadioEvents
>({
  tagName: 'my-radio',
  elementClass: MyRadioElement,
  // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
  react: React,
  events: {
    onIonFocus: 'ionFocus',
    onIonBlur: 'ionBlur',
  } as MyRadioEvents,
  defineCustomElement: defineMyRadio,
});
