'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type MyRangeCustomEvent, type RangeChangeEventDetail } from 'component-library';
import {
  MyRange as MyRangeElement,
  defineCustomElement as defineMyRange,
} from 'component-library/components/my-range.js';
import React from 'react';

export type MyRangeEvents = {
  onMyChange: EventName<MyRangeCustomEvent<RangeChangeEventDetail>>;
  onMyFocus: EventName<CustomEvent<void>>;
  onMyBlur: EventName<CustomEvent<void>>;
};

export const MyRange: StencilReactComponent<MyRangeElement, MyRangeEvents> = /*@__PURE__*/ createComponent<
  MyRangeElement,
  MyRangeEvents
>({
  tagName: 'my-range',
  elementClass: MyRangeElement,
  // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
  react: React,
  events: {
    onMyChange: 'myChange',
    onMyFocus: 'myFocus',
    onMyBlur: 'myBlur',
  } as MyRangeEvents,
  defineCustomElement: defineMyRange,
});
