'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import {
  MyToggle as MyToggleElement,
  defineCustomElement as defineMyToggle,
} from 'component-library/components/my-toggle.js';
import React from 'react';

export type MyToggleEvents = NonNullable<unknown>;

export const MyToggle: StencilReactComponent<MyToggleElement, MyToggleEvents> = /*@__PURE__*/ createComponent<
  MyToggleElement,
  MyToggleEvents
>({
  tagName: 'my-toggle',
  elementClass: MyToggleElement,
  // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
  react: React,
  events: {} as MyToggleEvents,
  defineCustomElement: defineMyToggle,
});
