import type { StencilWizardPlugin, WizardContext } from '@stencil/cli';
import { Project, SyntaxKind } from 'ts-morph';
import { access, mkdir, writeFile } from 'node:fs/promises';
import { join, relative, dirname } from 'node:path';

// ---------------------------------------------------------------------------
// ts-morph helpers
// ---------------------------------------------------------------------------

function amendStencilConfig(configPath: string, targetCode: string, mode: 'lazy' | 'standalone'): boolean {
  const project = new Project({ skipAddingFilesFromTsConfig: true });
  const src = project.addSourceFileAtPath(configPath);

  if (!src.getImportDeclaration('@stencil/vue-output-target')) {
    src.addImportDeclaration({ moduleSpecifier: '@stencil/vue-output-target', namedImports: ['vueOutputTarget'] });
  }

  const existingProp = src
    .getDescendantsOfKind(SyntaxKind.PropertyAssignment)
    .find((p) => p.getName() === 'outputTargets');

  if (!existingProp) {
    const configObj =
      src.getVariableDeclaration('config')?.getInitializerIfKind(SyntaxKind.ObjectLiteralExpression) ??
      src
        .getDescendantsOfKind(SyntaxKind.ObjectLiteralExpression)
        .find((obj) => obj.getProperty('namespace') !== undefined);
    if (!configObj) throw new Error('Could not find Stencil config object in stencil.config.ts');
    configObj.addPropertyAssignment({ name: 'outputTargets', initializer: '[]' });
  }

  const prop = src.getDescendantsOfKind(SyntaxKind.PropertyAssignment).find((p) => p.getName() === 'outputTargets')!;
  const arr = prop.getInitializerIfKind(SyntaxKind.ArrayLiteralExpression);
  if (!arr) throw new Error('outputTargets is not an array literal in stencil.config.ts');

  const existing = arr.getText();
  const alreadyAdded = existing.includes('vueOutputTarget(');

  const elements = arr.getElements().map((e) => e.getText().trim());

  if (mode === 'standalone') {
    const hasStandalone =
      existing.includes("type: 'standalone'") ||
      existing.includes('type: "standalone"') ||
      existing.includes("type: 'dist-custom-elements'") ||
      existing.includes('type: "dist-custom-elements"');
    if (!hasStandalone) elements.push("{ type: 'standalone' }");
  } else {
    const hasLoaderBundle =
      existing.includes("type: 'loader-bundle'") ||
      existing.includes('type: "loader-bundle"') ||
      existing.includes("type: 'dist'") ||
      existing.includes('type: "dist"');
    if (!hasLoaderBundle) elements.push("{ type: 'loader-bundle' }");
  }

  if (!alreadyAdded) elements.push(targetCode);

  prop.setInitializer(`[\n${elements.map((e) => `  ${e}`).join(',\n')},\n]`);
  src.formatText();
  src.saveSync();

  return !alreadyAdded;
}

// ---------------------------------------------------------------------------
// Wrapper package scaffolding
// ---------------------------------------------------------------------------

async function pathExists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

async function scaffoldWrapperPackage(
  wrapperDir: string,
  packageName: string,
  corePackageName: string,
  corePkgVersion: string
): Promise<void> {
  await mkdir(join(wrapperDir, 'src'), { recursive: true });

  const pkgJson = {
    name: packageName,
    version: '0.0.1',
    type: 'module',
    main: './dist/index.js',
    types: './dist/index.d.ts',
    exports: { '.': { types: './dist/index.d.ts', import: './dist/index.js' } },
    scripts: { build: 'tsc', dev: 'tsc --watch' },
    peerDependencies: { vue: '^3.4.0' },
    dependencies: { [corePackageName]: corePkgVersion },
    devDependencies: { typescript: '>=4 <7' },
  };

  const tsConfig = {
    compilerOptions: {
      target: 'ES2022',
      module: 'esnext',
      moduleResolution: 'bundler',
      declaration: true,
      rootDir: 'src',
      outDir: 'dist',
      strict: true,
      skipLibCheck: true,
    },
    include: ['src/**/*.ts'],
  };

  const indexTs =
    `// Re-exports Vue wrappers generated by @stencil/vue-output-target.\n` +
    `// src/components.ts is populated by \`stencil build\` — do not edit manually.\n` +
    `export * from './components.js';\n`;

  await Promise.all([
    writeFile(join(wrapperDir, '.gitignore'), 'dist/\nnode_modules/\n', 'utf8'),
    writeFile(join(wrapperDir, 'package.json'), JSON.stringify(pkgJson, null, 2) + '\n', 'utf8'),
    writeFile(join(wrapperDir, 'tsconfig.json'), JSON.stringify(tsConfig, null, 2) + '\n', 'utf8'),
    writeFile(join(wrapperDir, 'src', 'index.ts'), indexTs, 'utf8'),
  ]);
}

// ---------------------------------------------------------------------------
// Wizard
// ---------------------------------------------------------------------------

export const wizard = {
  init: {
    id: '@stencil/vue-output-target',
    displayName: 'Vue',
    description: 'Type-safe Vue 3 wrappers for your Stencil components',

    async run({ config, workspaceRoot, prompts, nypm }: WizardContext): Promise<void> {
      const { intro, outro, text, select, confirm, spinner, isCancel, cancel, log } = prompts;

      intro('Vue output target');

      const stencilConfigPath = join(config.rootDir, 'stencil.config.ts');

      // Guard: already configured?
      const guardProject = new Project({ skipAddingFilesFromTsConfig: true });
      const alreadyConfigured = guardProject
        .addSourceFileAtPath(stencilConfigPath)
        .getDescendantsOfKind(SyntaxKind.PropertyAssignment)
        .find((p) => p.getName() === 'outputTargets')
        ?.getInitializerIfKind(SyntaxKind.ArrayLiteralExpression)
        ?.getText()
        .includes('vueOutputTarget(');

      if (alreadyConfigured) {
        const redo = await confirm({
          message: 'vueOutputTarget is already in stencil.config.ts — reconfigure?',
          initialValue: false,
        });
        if (isCancel(redo) || !redo) {
          cancel('Skipping Vue setup.');
          return;
        }
      }

      // Where should the wrapper package live?
      let wrapperDir: string;
      const defaultName = `${config.fsNamespace}-vue`;

      if (workspaceRoot) {
        const rawName = await text({
          message: 'Wrapper package name?',
          placeholder: defaultName,
          defaultValue: defaultName,
        });
        if (isCancel(rawName)) {
          cancel('Setup cancelled.');
          return;
        }
        wrapperDir = join(dirname(config.rootDir), rawName as string);
      } else {
        const defaultRel = `../${config.fsNamespace}-vue`;
        const rawDir = await text({
          message: 'Wrapper package directory? (relative to stencil.config.ts)',
          placeholder: defaultRel,
          defaultValue: defaultRel,
        });
        if (isCancel(rawDir)) {
          cancel('Setup cancelled.');
          return;
        }
        wrapperDir = join(config.rootDir, rawDir as string);
      }

      // Loading mode
      const mode = await select({
        message: 'How should Vue load your components?',
        options: [
          {
            value: 'lazy',
            label: 'Lazy (loader-bundle)',
            hint: 'Components loaded on demand — recommended for most apps',
          },
          { value: 'standalone', label: 'Standalone', hint: 'All component code bundled — better for tree-shaking' },
        ],
      });
      if (isCancel(mode)) {
        cancel('Setup cancelled.');
        return;
      }

      // proxiesFile is the single file stencil writes all Vue wrappers into
      const proxiesFile = relative(config.rootDir, join(wrapperDir, 'src', 'components.ts')).replace(/\\/g, '/');

      // Scaffold wrapper package if the directory doesn't exist yet
      const shouldScaffold = !(await pathExists(wrapperDir));
      if (shouldScaffold) {
        const s = spinner();
        s.start(`Scaffolding wrapper package at ${relative(workspaceRoot ?? config.rootDir, wrapperDir)}`);
        try {
          const corePkgVersion = workspaceRoot
            ? 'workspace:*'
            : `file:${relative(wrapperDir, config.rootDir).replace(/\\/g, '/')}`;
          await scaffoldWrapperPackage(wrapperDir, `${config.fsNamespace}-vue`, config.fsNamespace, corePkgVersion);
          s.stop('Wrapper package scaffolded');
        } catch (e) {
          s.stop('Scaffolding failed — continuing');
          log.warn(`Could not scaffold wrapper package: ${e}`);
        }
      }

      // Build target config
      const lines = [
        `proxiesFile: '${proxiesFile}'`,
        `componentCorePackage: '${config.fsNamespace}'`,
        ...(mode === 'standalone'
          ? [
              `includeImportCustomElements: true`,
              `includeDefineCustomElements: false`,
              `customElementsDir: 'dist/standalone'`,
            ]
          : []),
      ];
      const targetCode = `vueOutputTarget({\n  ${lines.join(',\n  ')},\n})`;

      // Amend stencil.config.ts in one pass so formatText() sees the final array
      try {
        const added = amendStencilConfig(stencilConfigPath, targetCode, mode as 'lazy' | 'standalone');
        log.success(added ? 'stencil.config.ts updated' : 'vueOutputTarget already present — no changes made');
      } catch (e) {
        log.warn(
          `Could not automatically update stencil.config.ts (${e}). Add manually:\n\n` +
            `import { vueOutputTarget } from '@stencil/vue-output-target';\n` +
            `// in outputTargets:\n${targetCode}`
        );
      }

      // Install deps
      log.info('Installing @stencil/vue-output-target...');
      await nypm.addDependency(['@stencil/vue-output-target'], { cwd: config.rootDir, dev: true });
      log.success('Installed @stencil/vue-output-target');

      if (shouldScaffold && (await pathExists(wrapperDir))) {
        log.info('Installing Vue peer dependencies in wrapper package...');
        await nypm.addDependency(['@stencil/vue-output-target'], { cwd: wrapperDir });
        await nypm.addDependency(['vue', 'typescript'], { cwd: wrapperDir, dev: true });
        log.success('Vue peer dependencies installed');
      }

      outro('Vue output target configured');
    },
  },
} satisfies StencilWizardPlugin;
