import type { StencilWizardPlugin, WizardContext } from '@stencil/cli';
import { access, mkdir, writeFile } from 'node:fs/promises';
import { join, relative, dirname } from 'node:path';

// ---------------------------------------------------------------------------
// Wrapper package scaffolding
// ---------------------------------------------------------------------------

async function pathExists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

async function scaffoldWrapperPackage(
  wrapperDir: string,
  packageName: string,
  corePackageName: string,
  corePkgVersion: string
): Promise<void> {
  await mkdir(join(wrapperDir, 'src'), { recursive: true });

  const pkgJson = {
    name: packageName,
    version: '0.0.1',
    type: 'module',
    main: './dist/index.js',
    types: './dist/index.d.ts',
    exports: { '.': { types: './dist/index.d.ts', import: './dist/index.js' } },
    scripts: { build: 'tsc', dev: 'tsc --watch' },
    peerDependencies: { vue: '^3.4.0' },
    dependencies: { [corePackageName]: corePkgVersion },
    devDependencies: { typescript: '>=4 <7' },
  };

  const tsConfig = {
    compilerOptions: {
      target: 'ES2022',
      module: 'esnext',
      moduleResolution: 'bundler',
      declaration: true,
      rootDir: 'src',
      outDir: 'dist',
      strict: true,
      skipLibCheck: true,
    },
    include: ['src/**/*.ts'],
  };

  const indexTs =
    `// Re-exports Vue wrappers generated by @stencil/vue-output-target.\n` +
    `// src/components.ts is populated by \`stencil build\` — do not edit manually.\n` +
    `export * from './components.js';\n`;

  await Promise.all([
    writeFile(join(wrapperDir, '.gitignore'), 'dist/\nnode_modules/\n', 'utf8'),
    writeFile(join(wrapperDir, 'package.json'), JSON.stringify(pkgJson, null, 2) + '\n', 'utf8'),
    writeFile(join(wrapperDir, 'tsconfig.json'), JSON.stringify(tsConfig, null, 2) + '\n', 'utf8'),
    writeFile(join(wrapperDir, 'src', 'index.ts'), indexTs, 'utf8'),
  ]);
}

// ---------------------------------------------------------------------------
// Wizard
// ---------------------------------------------------------------------------

export const wizard = {
  init: {
    id: '@stencil/vue-output-target',
    displayName: 'Vue',
    description: 'Type-safe Vue 3 wrappers for your Stencil components',

    async run({ config, workspaceRoot, prompts, nypm, openStencilConfig }: WizardContext): Promise<void> {
      const { intro, outro, text, select, confirm, spinner, isCancel, cancel, log } = prompts;

      intro('Vue output target');

      // Guard: already configured?
      const editor = await openStencilConfig();
      const alreadyConfigured = editor.outputTargetsContains('vueOutputTarget(');

      if (alreadyConfigured) {
        const redo = await confirm({
          message: 'vueOutputTarget is already in stencil.config.ts — reconfigure?',
          initialValue: false,
        });
        if (isCancel(redo) || !redo) {
          cancel('Skipping Vue setup.');
          return;
        }
      }

      // Where should the wrapper package live?
      let wrapperDir: string;
      let wrapperPackageName = `${config.fsNamespace}-vue`;

      if (workspaceRoot) {
        const rawName = await text({
          message: 'Wrapper package name?',
          placeholder: wrapperPackageName,
          defaultValue: wrapperPackageName,
        });
        if (isCancel(rawName)) {
          cancel('Setup cancelled.');
          return;
        }
        wrapperPackageName = rawName as string;
        // Directory is already namespaced by living under packages/, so keep it
        // short rather than repeating the fsNamespace prefix from the package name.
        wrapperDir = join(dirname(config.rootDir), 'vue');
      } else {
        const defaultRel = `../${config.fsNamespace}-vue`;
        const rawDir = await text({
          message: 'Wrapper package directory? (relative to stencil.config.ts)',
          placeholder: defaultRel,
          defaultValue: defaultRel,
        });
        if (isCancel(rawDir)) {
          cancel('Setup cancelled.');
          return;
        }
        wrapperDir = join(config.rootDir, rawDir as string);
      }

      // Loading mode
      const mode = await select({
        message: 'How should Vue load your components?',
        options: [
          {
            value: 'lazy',
            label: 'Lazy (loader-bundle)',
            hint: 'Components loaded on demand — recommended for most apps',
          },
          { value: 'standalone', label: 'Standalone', hint: 'All component code bundled — better for tree-shaking' },
        ],
      });
      if (isCancel(mode)) {
        cancel('Setup cancelled.');
        return;
      }

      // proxiesFile is the single file stencil writes all Vue wrappers into
      const proxiesFile = relative(config.rootDir, join(wrapperDir, 'src', 'components.ts')).replace(/\\/g, '/');

      // Scaffold wrapper package if the directory doesn't exist yet
      const shouldScaffold = !(await pathExists(wrapperDir));
      if (shouldScaffold) {
        const s = spinner();
        s.start(`Scaffolding wrapper package at ${relative(workspaceRoot ?? config.rootDir, wrapperDir)}`);
        try {
          // workspace:* only resolves under pnpm/yarn-berry/bun — npm and yarn classic reject
          // the protocol outright (even for devDependencies that are never installed), so only
          // use it when the detected package manager actually understands it.
          const pm = workspaceRoot ? await nypm.detectPackageManager(workspaceRoot) : undefined;
          const supportsWorkspaceProtocol =
            pm?.name === 'pnpm' || pm?.name === 'bun' || (pm?.name === 'yarn' && pm.majorVersion !== '1');
          const corePkgVersion = supportsWorkspaceProtocol
            ? 'workspace:*'
            : `file:${relative(wrapperDir, config.rootDir).replace(/\\/g, '/')}`;
          await scaffoldWrapperPackage(wrapperDir, wrapperPackageName, config.fsNamespace, corePkgVersion);
          s.stop('Wrapper package scaffolded');
        } catch (e) {
          s.stop('Scaffolding failed — continuing');
          log.warn(`Could not scaffold wrapper package: ${e}`);
        }
      }

      // Build target config
      const lines = [
        `proxiesFile: '${proxiesFile}'`,
        `componentCorePackage: '${config.fsNamespace}'`,
        ...(mode === 'standalone'
          ? [
              `includeImportCustomElements: true`,
              `includeDefineCustomElements: false`,
              `customElementsDir: 'dist/standalone'`,
            ]
          : []),
      ];
      const targetCode = `vueOutputTarget({\n  ${lines.join(',\n  ')},\n})`;

      // Amend stencil.config.ts
      try {
        editor.addImport('@stencil/vue-output-target', ['vueOutputTarget']);

        const hasRequiredTarget =
          mode === 'standalone'
            ? editor.outputTargetsContains("type: 'standalone'") ||
              editor.outputTargetsContains('type: "standalone"') ||
              editor.outputTargetsContains("type: 'dist-custom-elements'") ||
              editor.outputTargetsContains('type: "dist-custom-elements"')
            : editor.outputTargetsContains("type: 'loader-bundle'") ||
              editor.outputTargetsContains('type: "loader-bundle"') ||
              editor.outputTargetsContains("type: 'dist'") ||
              editor.outputTargetsContains('type: "dist"');
        if (!hasRequiredTarget) {
          editor.addOutputTarget(mode === 'standalone' ? "{ type: 'standalone' }" : "{ type: 'loader-bundle' }");
        }

        if (!editor.replaceOutputTarget('vueOutputTarget(', targetCode)) {
          editor.addOutputTarget(targetCode);
        }

        await editor.save();
        log.success('stencil.config.ts updated');
      } catch (e) {
        log.warn(
          `Could not automatically update stencil.config.ts (${e}). Add manually:\n\n` +
            `import { vueOutputTarget } from '@stencil/vue-output-target';\n` +
            `// in outputTargets:\n${targetCode}`
        );
      }

      // Install deps
      log.info('Installing @stencil/vue-output-target...');
      await nypm.addDependency(['@stencil/vue-output-target'], { cwd: config.rootDir, dev: true });
      log.success('Installed @stencil/vue-output-target');

      if (shouldScaffold && (await pathExists(wrapperDir))) {
        log.info('Installing Vue peer dependencies in wrapper package...');
        await nypm.addDependency(['@stencil/vue-output-target'], { cwd: wrapperDir });
        await nypm.addDependency(['vue', 'typescript'], { cwd: wrapperDir, dev: true });
        log.success('Vue peer dependencies installed');
      }

      outro('Vue output target configured');
    },
  },
} satisfies StencilWizardPlugin;
