'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { getTagTransformer } from './tag-transformer.js';

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

import { type CheckboxChangeEventDetail, type CheckboxChangeNestedEventDetail, type IMyComponent, type InputChangeEventDetail, type MyButtonCustomEvent, type MyButtonScopedCustomEvent, type MyCheckboxCustomEvent, type MyComponentScopedCustomEvent, type MyCounterCustomEvent, type MyInputCustomEvent, type MyInputScopedCustomEvent, type MyPopoverCustomEvent, type MyRadioCustomEvent, type MyRadioGroupCustomEvent, type MyRangeCustomEvent, type OverlayEventDetail, type RadioGroupChangeEventDetail, type RangeChangeEventDetail } from "component-library";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "component-library-react";
import type { Components } from "component-library/components";
import { MyButtonScoped as MyButtonScopedElement } from "component-library/components/my-button-scoped.js";
import { MyButton as MyButtonElement } from "component-library/components/my-button.js";
import { MyCheckbox as MyCheckboxElement } from "component-library/components/my-checkbox.js";
import { MyComplexPropsScoped as MyComplexPropsScopedElement } from "component-library/components/my-complex-props-scoped.js";
import { MyComplexProps as MyComplexPropsElement } from "component-library/components/my-complex-props.js";
import { MyComponentScoped as MyComponentScopedElement } from "component-library/components/my-component-scoped.js";
import { MyComponent as MyComponentElement } from "component-library/components/my-component.js";
import { MyCounter as MyCounterElement } from "component-library/components/my-counter.js";
import { MyInputScoped as MyInputScopedElement } from "component-library/components/my-input-scoped.js";
import { MyInput as MyInputElement } from "component-library/components/my-input.js";
import { MyListItemScoped as MyListItemScopedElement } from "component-library/components/my-list-item-scoped.js";
import { MyListItem as MyListItemElement } from "component-library/components/my-list-item.js";
import { MyListScoped as MyListScopedElement } from "component-library/components/my-list-scoped.js";
import { MyList as MyListElement } from "component-library/components/my-list.js";
import { MyPopover as MyPopoverElement } from "component-library/components/my-popover.js";
import { MyRadioGroup as MyRadioGroupElement } from "component-library/components/my-radio-group.js";
import { MyRadio as MyRadioElement } from "component-library/components/my-radio.js";
import { MyRange as MyRangeElement } from "component-library/components/my-range.js";
import { MyToggleContent as MyToggleContentElement } from "component-library/components/my-toggle-content.js";
import { MyToggle as MyToggleElement } from "component-library/components/my-toggle.js";
import { MyTransformTest as MyTransformTestElement } from "component-library/components/my-transform-test.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { "scoped": ["my-counter"], "default": "declarative-shadow-dom" };

export type MyButtonEvents = {
    onMyFocus: EventName<MyButtonCustomEvent<void>>,
    onMyBlur: EventName<MyButtonCustomEvent<void>>
};

export const MyButton: StencilReactComponent<MyButtonElement, Components.MyButton, MyButtonEvents> = /*@__PURE__*/ createComponent<MyButtonElement, Components.MyButton, MyButtonEvents>({
    tagName: 'my-button',
    properties: {
        color: 'color',
        buttonType: 'button-type',
        disabled: 'disabled',
        expand: 'expand',
        fill: 'fill',
        download: 'download',
        href: 'href',
        rel: 'rel',
        shape: 'shape',
        size: 'size',
        strong: 'strong',
        target: 'target',
        type: 'type'
    },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyButton as StencilReactComponent<MyButtonElement, Components.MyButton, MyButtonEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyButtonScopedEvents = {
    onMyFocus: EventName<MyButtonScopedCustomEvent<void>>,
    onMyBlur: EventName<MyButtonScopedCustomEvent<void>>
};

export const MyButtonScoped: StencilReactComponent<MyButtonScopedElement, Components.MyButtonScoped, MyButtonScopedEvents> = /*@__PURE__*/ createComponent<MyButtonScopedElement, Components.MyButtonScoped, MyButtonScopedEvents>({
    tagName: 'my-button-scoped',
    properties: {
        color: 'color',
        buttonType: 'button-type',
        disabled: 'disabled',
        expand: 'expand',
        fill: 'fill',
        download: 'download',
        href: 'href',
        rel: 'rel',
        shape: 'shape',
        size: 'size',
        strong: 'strong',
        target: 'target',
        type: 'type'
    },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyButtonScoped as StencilReactComponent<MyButtonScopedElement, Components.MyButtonScoped, MyButtonScopedEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyCheckboxEvents = {
    onIonChange: EventName<MyCheckboxCustomEvent<CheckboxChangeEventDetail>>,
    onIonChangeNested: EventName<MyCheckboxCustomEvent<CheckboxChangeNestedEventDetail>>,
    onIonFocus: EventName<MyCheckboxCustomEvent<void>>,
    onIonBlur: EventName<MyCheckboxCustomEvent<void>>
};

export const MyCheckbox: StencilReactComponent<MyCheckboxElement, Components.MyCheckbox, MyCheckboxEvents> = /*@__PURE__*/ createComponent<MyCheckboxElement, Components.MyCheckbox, MyCheckboxEvents>({
    tagName: 'my-checkbox',
    properties: {
        color: 'color',
        name: 'name',
        checked: 'checked',
        indeterminate: 'indeterminate',
        disabled: 'disabled',
        value: 'value',
        labelPlacement: 'label-placement',
        justify: 'justify',
        alignment: 'alignment'
    },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyCheckbox as StencilReactComponent<MyCheckboxElement, Components.MyCheckbox, MyCheckboxEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyComplexPropsEvents = NonNullable<unknown>;

export const MyComplexProps: StencilReactComponent<MyComplexPropsElement, Components.MyComplexProps, MyComplexPropsEvents> = /*@__PURE__*/ createComponent<MyComplexPropsElement, Components.MyComplexProps, MyComplexPropsEvents>({
    tagName: 'my-complex-props',
    properties: { grault: 'grault' },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyComplexProps as StencilReactComponent<MyComplexPropsElement, Components.MyComplexProps, MyComplexPropsEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyComplexPropsScopedEvents = NonNullable<unknown>;

export const MyComplexPropsScoped: StencilReactComponent<MyComplexPropsScopedElement, Components.MyComplexPropsScoped, MyComplexPropsScopedEvents> = /*@__PURE__*/ createComponent<MyComplexPropsScopedElement, Components.MyComplexPropsScoped, MyComplexPropsScopedEvents>({
    tagName: 'my-complex-props-scoped',
    properties: { grault: 'grault' },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyComplexPropsScoped as StencilReactComponent<MyComplexPropsScopedElement, Components.MyComplexPropsScoped, MyComplexPropsScopedEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, Components.MyComponent, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, Components.MyComponent, MyComponentEvents>({
    tagName: 'my-component',
    properties: {
        first: 'first',
        middleName: 'middle-name',
        last: 'last'
    },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyComponent as StencilReactComponent<MyComponentElement, Components.MyComponent, MyComponentEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyComponentScopedEvents = { onMyCustomEvent: EventName<MyComponentScopedCustomEvent<IMyComponent.someVar>> };

export const MyComponentScoped: StencilReactComponent<MyComponentScopedElement, Components.MyComponentScoped, MyComponentScopedEvents> = /*@__PURE__*/ createComponent<MyComponentScopedElement, Components.MyComponentScoped, MyComponentScopedEvents>({
    tagName: 'my-component-scoped',
    properties: {
        first: 'first',
        middleName: 'middle-name',
        last: 'last'
    },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyComponentScoped as StencilReactComponent<MyComponentScopedElement, Components.MyComponentScoped, MyComponentScopedEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyCounterEvents = { onCount: EventName<MyCounterCustomEvent<number>> };

export const MyCounter: StencilReactComponent<MyCounterElement, Components.MyCounter, MyCounterEvents> = /*@__PURE__*/ createComponent<MyCounterElement, Components.MyCounter, MyCounterEvents>({
    tagName: 'my-counter',
    properties: { startValue: 'start-value' },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyCounter as StencilReactComponent<MyCounterElement, Components.MyCounter, MyCounterEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyInputEvents = {
    onMyInput: EventName<MyInputCustomEvent<KeyboardEvent>>,
    onMyChange: EventName<MyInputCustomEvent<InputChangeEventDetail>>,
    onMyBlur: EventName<MyInputCustomEvent<void>>,
    onMyFocus: EventName<MyInputCustomEvent<void>>
};

export const MyInput: StencilReactComponent<MyInputElement, Components.MyInput, MyInputEvents> = /*@__PURE__*/ createComponent<MyInputElement, Components.MyInput, MyInputEvents>({
    tagName: 'my-input',
    properties: {
        color: 'color',
        accept: 'accept',
        autocapitalize: 'autocapitalize',
        autocomplete: 'autocomplete',
        autocorrect: 'autocorrect',
        autofocus: 'autofocus',
        clearInput: 'clear-input',
        clearOnEdit: 'clear-on-edit',
        disabled: 'disabled',
        enterkeyhint: 'enterkeyhint',
        inputmode: 'inputmode',
        max: 'max',
        maxlength: 'maxlength',
        min: 'min',
        minlength: 'minlength',
        multiple: 'multiple',
        name: 'name',
        pattern: 'pattern',
        placeholder: 'placeholder',
        readonly: 'readonly',
        required: 'required',
        spellcheck: 'spellcheck',
        step: 'step',
        size: 'size',
        type: 'type',
        value: 'value'
    },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyInput as StencilReactComponent<MyInputElement, Components.MyInput, MyInputEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyInputScopedEvents = {
    onMyInput: EventName<MyInputScopedCustomEvent<KeyboardEvent>>,
    onMyChange: EventName<MyInputScopedCustomEvent<InputChangeEventDetail>>,
    onMyBlur: EventName<MyInputScopedCustomEvent<void>>,
    onMyFocus: EventName<MyInputScopedCustomEvent<void>>
};

export const MyInputScoped: StencilReactComponent<MyInputScopedElement, Components.MyInputScoped, MyInputScopedEvents> = /*@__PURE__*/ createComponent<MyInputScopedElement, Components.MyInputScoped, MyInputScopedEvents>({
    tagName: 'my-input-scoped',
    properties: {
        color: 'color',
        accept: 'accept',
        autocapitalize: 'autocapitalize',
        autocomplete: 'autocomplete',
        autocorrect: 'autocorrect',
        autofocus: 'autofocus',
        clearInput: 'clear-input',
        clearOnEdit: 'clear-on-edit',
        disabled: 'disabled',
        enterkeyhint: 'enterkeyhint',
        inputmode: 'inputmode',
        max: 'max',
        maxlength: 'maxlength',
        min: 'min',
        minlength: 'minlength',
        multiple: 'multiple',
        name: 'name',
        pattern: 'pattern',
        placeholder: 'placeholder',
        readonly: 'readonly',
        required: 'required',
        spellcheck: 'spellcheck',
        step: 'step',
        size: 'size',
        type: 'type',
        value: 'value'
    },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyInputScoped as StencilReactComponent<MyInputScopedElement, Components.MyInputScoped, MyInputScopedEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyListEvents = NonNullable<unknown>;

export const MyList: StencilReactComponent<MyListElement, Components.MyList, MyListEvents> = /*@__PURE__*/ createComponent<MyListElement, Components.MyList, MyListEvents>({
    tagName: 'my-list',
    properties: {},
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyList as StencilReactComponent<MyListElement, Components.MyList, MyListEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyListItemEvents = NonNullable<unknown>;

export const MyListItem: StencilReactComponent<MyListItemElement, Components.MyListItem, MyListItemEvents> = /*@__PURE__*/ createComponent<MyListItemElement, Components.MyListItem, MyListItemEvents>({
    tagName: 'my-list-item',
    properties: {},
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyListItem as StencilReactComponent<MyListItemElement, Components.MyListItem, MyListItemEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyListItemScopedEvents = NonNullable<unknown>;

export const MyListItemScoped: StencilReactComponent<MyListItemScopedElement, Components.MyListItemScoped, MyListItemScopedEvents> = /*@__PURE__*/ createComponent<MyListItemScopedElement, Components.MyListItemScoped, MyListItemScopedEvents>({
    tagName: 'my-list-item-scoped',
    properties: {},
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyListItemScoped as StencilReactComponent<MyListItemScopedElement, Components.MyListItemScoped, MyListItemScopedEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyListScopedEvents = NonNullable<unknown>;

export const MyListScoped: StencilReactComponent<MyListScopedElement, Components.MyListScoped, MyListScopedEvents> = /*@__PURE__*/ createComponent<MyListScopedElement, Components.MyListScoped, MyListScopedEvents>({
    tagName: 'my-list-scoped',
    properties: {},
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyListScoped as StencilReactComponent<MyListScopedElement, Components.MyListScoped, MyListScopedEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyPopoverEvents = {
    onMyPopoverDidPresent: EventName<MyPopoverCustomEvent<void>>,
    onMyPopoverWillPresent: EventName<MyPopoverCustomEvent<void>>,
    onMyPopoverWillDismiss: EventName<MyPopoverCustomEvent<OverlayEventDetail>>,
    onMyPopoverDidDismiss: EventName<MyPopoverCustomEvent<OverlayEventDetail>>
};

export const MyPopover: StencilReactComponent<MyPopoverElement, Components.MyPopover, MyPopoverEvents> = /*@__PURE__*/ createComponent<MyPopoverElement, Components.MyPopover, MyPopoverEvents>({
    tagName: 'my-popover',
    properties: {
        component: 'component',
        keyboardClose: 'keyboard-close',
        cssClass: 'css-class',
        backdropDismiss: 'backdrop-dismiss',
        event: 'event',
        showBackdrop: 'show-backdrop',
        translucent: 'translucent',
        animated: 'animated'
    },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyPopover as StencilReactComponent<MyPopoverElement, Components.MyPopover, MyPopoverEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyRadioEvents = {
    onIonFocus: EventName<MyRadioCustomEvent<void>>,
    onIonBlur: EventName<MyRadioCustomEvent<void>>
};

export const MyRadio: StencilReactComponent<MyRadioElement, Components.MyRadio, MyRadioEvents> = /*@__PURE__*/ createComponent<MyRadioElement, Components.MyRadio, MyRadioEvents>({
    tagName: 'my-radio',
    properties: {
        color: 'color',
        name: 'name',
        disabled: 'disabled',
        value: 'value',
        labelPlacement: 'label-placement',
        justify: 'justify',
        alignment: 'alignment'
    },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyRadio as StencilReactComponent<MyRadioElement, Components.MyRadio, MyRadioEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyRadioGroupEvents = { onMyChange: EventName<MyRadioGroupCustomEvent<RadioGroupChangeEventDetail>> };

export const MyRadioGroup: StencilReactComponent<MyRadioGroupElement, Components.MyRadioGroup, MyRadioGroupEvents> = /*@__PURE__*/ createComponent<MyRadioGroupElement, Components.MyRadioGroup, MyRadioGroupEvents>({
    tagName: 'my-radio-group',
    properties: {
        allowEmptySelection: 'allow-empty-selection',
        compareWith: 'compare-with',
        name: 'name',
        value: 'value'
    },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyRadioGroup as StencilReactComponent<MyRadioGroupElement, Components.MyRadioGroup, MyRadioGroupEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyRangeEvents = {
    onMyChange: EventName<MyRangeCustomEvent<RangeChangeEventDetail>>,
    onMyFocus: EventName<MyRangeCustomEvent<void>>,
    onMyBlur: EventName<MyRangeCustomEvent<void>>
};

export const MyRange: StencilReactComponent<MyRangeElement, Components.MyRange, MyRangeEvents> = /*@__PURE__*/ createComponent<MyRangeElement, Components.MyRange, MyRangeEvents>({
    tagName: 'my-range',
    properties: {
        color: 'color',
        debounce: 'debounce',
        name: 'name',
        dualKnobs: 'dual-knobs',
        min: 'min',
        max: 'max',
        pin: 'pin',
        snaps: 'snaps',
        step: 'step',
        ticks: 'ticks',
        disabled: 'disabled',
        value: 'value'
    },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyRange as StencilReactComponent<MyRangeElement, Components.MyRange, MyRangeEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyToggleEvents = NonNullable<unknown>;

export const MyToggle: StencilReactComponent<MyToggleElement, Components.MyToggle, MyToggleEvents> = /*@__PURE__*/ createComponent<MyToggleElement, Components.MyToggle, MyToggleEvents>({
    tagName: 'my-toggle',
    properties: {},
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyToggle as StencilReactComponent<MyToggleElement, Components.MyToggle, MyToggleEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyToggleContentEvents = NonNullable<unknown>;

export const MyToggleContent: StencilReactComponent<MyToggleContentElement, Components.MyToggleContent, MyToggleContentEvents> = /*@__PURE__*/ createComponent<MyToggleContentElement, Components.MyToggleContent, MyToggleContentEvents>({
    tagName: 'my-toggle-content',
    properties: { visible: 'visible' },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyToggleContent as StencilReactComponent<MyToggleContentElement, Components.MyToggleContent, MyToggleContentEvents>,
    serializeShadowRoot,
    getTagTransformer
});

export type MyTransformTestEvents = NonNullable<unknown>;

export const MyTransformTest: StencilReactComponent<MyTransformTestElement, Components.MyTransformTest, MyTransformTestEvents> = /*@__PURE__*/ createComponent<MyTransformTestElement, Components.MyTransformTest, MyTransformTestEvents>({
    tagName: 'my-transform-test',
    properties: { message: 'message' },
    hydrateModule: import('component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.MyTransformTest as StencilReactComponent<MyTransformTestElement, Components.MyTransformTest, MyTransformTestEvents>,
    serializeShadowRoot,
    getTagTransformer
});
