name: 'Production Release'

on:
  workflow_dispatch:
    inputs:
      package:
        required: true
        type: choice
        description: Which package should be published?
        options:
          - vue
          - angular
          - react
          - ssr
          - types
      tag:
        required: true
        type: choice
        description: Which npm tag should this be published to?
        options:
          - latest
          - next
      preid:
        type: choice
        description: Which prerelease identifier should be used? This is only needed when version is "prepatch", "preminor", "premajor", or "prerelease".
        default: ''
        options:
          - '' # no prerelease
          - alpha
          - beta
          - rc
          - next
jobs:
  prod-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: 📦 Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: 🟢 Use Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '24'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: 📦 Install Dependencies
        run: pnpm install
        shell: bash
      - name: 📦 Publish Package
        uses: ./.github/actions/publish-npm
        with:
          tag: ${{ inputs.tag }} # "latest" or "next"
          preid: ${{ inputs.preid }} # Only needed when version is "prepatch", "preminor", "premajor", or "prerelease"
          scope: ${{ inputs.package == 'ssr' && '@stencil/ssr' || format('@stencil/{0}-output-target', inputs.package) }}
          # Look at package.json's name
          # Coupled to project structure. Update this when adding a new output target.
          # Examples: vue-output-target, angular-output-target, react-output-target
          working-directory: './packages/${{ inputs.package }}' # Follow the repo structure

