name: Needs Reproduction

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  reproduire:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'needs reproduction'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4
      - uses: Hebilicious/reproduire@v0.0.9
        with:
          label: needs reproduction
